### ISSUE TITLE
Umbrella issue for plugin_test

### ISSUE THREAD

**Issue by imbsky** [asdf-community/.github#2]
Add `plugin_test` job for community plugins.

```yml
plugin_test:
  strategy:
    matrix:
      os: [ubuntu-latest, macos-latest]

  runs-on: ${{ matrix.os }}

  steps:
    - name: asdf_plugin_test
      uses: asdf-vm/actions/plugin-test@v1.0.0
      with:
        command: COMMAND --version
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

https://github.com/asdf-community/asdf-direnv/blob/master/.github/workflows/workflow.yml

- [x] [asdf-alp](https://github.com/asdf-community/asdf-alp) - @Naturalclar
- [x] [asdf-ccache](https://github.com/asdf-community/asdf-ccache) - @sasurau4
- [x] [asdf-deno](https://github.com/asdf-community/asdf-deno) - @sasurau4
- [x] [asdf-elm](https://github.com/asdf-community/asdf-elm) - @Haritaso
- [x] [asdf-fstar](https://github.com/asdf-community/asdf-fstar) - @Naturalclar
- [x] [asdf-lean](https://github.com/asdf-community/asdf-lean) - @sasurau4
- [x] [asdf-mlton](https://github.com/asdf-community/asdf-mlton) - @sasurau4
- [x] [asdf-ocaml](https://github.com/asdf-community/asdf-ocaml) - @nzws
- [x] [asdf-rlwrap](https://github.com/asdf-community/asdf-rlwrap) - @sasurau4
- [x] [asdf-zen](https://github.com/asdf-community/asdf-zen) - @imbsky
- [x] [asdf-aria2](https://github.com/asdf-community/asdf-aria2) - @sasurau4
- [x] [asdf-cue](https://github.com/asdf-community/asdf-cue) - @Naturalclar
- [x] [asdf-direnv](https://github.com/asdf-community/asdf-direnv) - @vic
- [x] [asdf-esy](https://github.com/asdf-community/asdf-esy) - @Naturalclar
- [x] [asdf-haxe](https://github.com/asdf-community/asdf-haxe) - @imbsky
- [x] [asdf-meson](https://github.com/asdf-community/asdf-meson) - @Naturalclar
- [x] [asdf-ninja](https://github.com/asdf-community/asdf-ninja) - @jeffryang24
- [x] [asdf-opam](https://github.com/asdf-community/asdf-opam) - @Naturalclar
- [x] [asdf-rust](https://github.com/asdf-community/asdf-rust) - @nesso-pfl
